# Google Sheets ID of the cards spreadsheet
sheet_gdid: ***

# Local path to the artwork folder
artwork_path: C:\Google Drive\CardImages\

# Path to GIMP console executable
gimp_console_path: C:\Program Files\GIMP 2\bin\gimp-console-2.10.exe

# Path to ImageMagick executable
magick_path: C:\Program Files\ImageMagick-7.0.10-Q16-HDRI\magick.exe

# Path to OCTGN set.xml destination folder (may be empty)
octgn_set_xml_destination_path: C:\Google Drive\Playtesting\OCTGN Files\Set Folders

# Path to OCTGN set.xml scratch destination folder (may be empty)
octgn_set_xml_scratch_destination_path: C:\Google Drive\Playtesting\OCTGN Files\Scratch Set Folders

# Path to OCTGN .o8d destination folder (may be empty)
octgn_o8d_destination_path: C:\Google Drive\Playtesting\OCTGN Files\Encounter Decks

# Path to OCTGN .o8d scratch destination folder (may be empty)
octgn_o8d_scratch_destination_path: C:\Google Drive\Playtesting\OCTGN Files\Scratch Encounter Decks

# Path to DB destination folder (may be empty)
db_destination_path: C:\Google Drive\RenderedImages

# Whether to reprocess all cards (true)
# or update only the cards, changed since the previous script run (false)
reprocess_all: true

# Process only "selected" rows (true or false)
selected_only: false

# Stop processing if there are no spreadsheet changes (true or false)
exit_if_no_spreadsheet_changes: false

# Number of parallel processes to use ("default" means "cpu_count() - 1")
parallelism: default

# List of set IDs to work on
set_ids:
  - all  # all non-scratch sets
#  - all_scratch  # all scratch sets
#  - 8a3273ca-1ccd-4e07-913b-766fcc49fe6f  # ALeP - Children of Eorl

# List of set IDs to ignore
ignore_set_ids:
#  - 8a3273ca-1ccd-4e07-913b-766fcc49fe6f  # ALeP - Children of Eorl

# Creating set.xml files for OCTGN (true or false)
octgn_set_xml: true

# Creating .o8d files for OCTGN (true or false)
octgn_o8d: true

# Creating CSV files for RingsDB (true or false)
ringsdb_csv: true

# Creating JSON files for Hall of Beorn (true or false)
hallofbeorn_json: true

# Creating CSV files for the French database sda.cgbuilder.fr (true or false)
frenchdb_csv: false

# Creating CSV files for the Spanish database susurrosdelbosqueviejo.com (true or false)
spanishdb_csv: false

# Updating test.ringsdb.com
update_ringsdb: false

# test.ringsdb.com URL
ringsdb_url: https://test.ringsdb.com

# test.ringsdb.com session id: <PHPSESSID>|<REMEMBERME>
ringsdb_sessionid: 

# List of image outputs
outputs:
  English:
#    - db
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - mbprint_7z
#    - mbprint_pdf_7z
#    - makeplayingcards_7z
#    - genericpng_7z
#    - genericpng_pdf_a4_7z
#    - genericpng_pdf_letter_7z
#    - rules_pdf
  German:
#    - db
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - mbprint_7z
#    - mbprint_pdf_7z
#    - makeplayingcards_7z
#    - genericpng_7z
#    - genericpng_pdf_a4_7z
#    - genericpng_pdf_letter_7z
#    - rules_pdf
  Spanish:
#    - db
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - mbprint_7z
#    - mbprint_pdf_7z
#    - makeplayingcards_7z
#    - genericpng_7z
#    - genericpng_pdf_a4_7z
#    - genericpng_pdf_letter_7z
#    - rules_pdf
  French:
#    - db
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - mbprint_7z
#    - mbprint_pdf_7z
#    - makeplayingcards_7z
#    - genericpng_7z
#    - genericpng_pdf_a4_7z
#    - genericpng_pdf_letter_7z
#    - rules_pdf
  Polish:
#    - db
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - mbprint_7z
#    - mbprint_pdf_7z
#    - makeplayingcards_7z
#    - genericpng_7z
#    - genericpng_pdf_a4_7z
#    - genericpng_pdf_letter_7z
#    - rules_pdf
  Italian:
#    - db
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - mbprint_7z
#    - mbprint_pdf_7z
#    - makeplayingcards_7z
#    - genericpng_7z
#    - genericpng_pdf_a4_7z
#    - genericpng_pdf_letter_7z
#    - rules_pdf
