# Google Drive ID of the cards spreadsheet (leave empty to use a local copy)
sheet_gdid: ***

# Local path to the artwork folder
artwork_path: C:\Google Drive\CardImages\

# Path to GIMP console executable
gimp_console_path: C:\Program Files\GIMP 2\bin\gimp-console-2.10.exe

# Path to ImageMagick executable
magick_path: C:\Program Files\ImageMagick-7.0.10-Q16-HDRI\magick.exe

# Path to OCTGN destination folder (may be empty)
octgn_destination_path: C:\Google Drive\OCTGN\

# Whether to reprocess all cards (true)
# or update only the cards, changed since the previous script run (false)
reprocess_all: true

# Process only "selected" rows (true or false)
selected_only: false

# Number of parallel processes to use ("default" means "cpu_count() - 1")
parallelism: default

# List of set IDs to work on
set_ids:
  - 8a3273ca-1ccd-4e07-913b-766fcc49fe6f  # ALeP - Children of Eorl
  - 17b90ca1-7e3e-4891-99da-954a7833e88e  # ALeP - The Aldburg Plot
  - 4eff45c3-8435-438f-bbbf-633483645dc6  # ALeP - Fire on the Eastemnet
  - 535a1083-330f-4bc5-a1bb-64c364da9e0a  # ALeP - The Gap of Rohan
  - 3e7002fc-f723-4f86-a625-548347b1eaa4  # ALeP - Mustering of the Rohirrim
  - 3104cd2a-ccce-44a7-bc6e-e3433636c329  # ALeP - The Glittering Caves
  - 6890e6e4-fffb-4765-9fe0-0e6bce22c9a4  # ALeP - Blood in the Isen
#  - all  # all non-scratch sets
#  - all_scratch  # all scratch sets

# Creating set.xml files for OCTGN (true or false)
octgn_set_xml: true

# Creating .o8d files for OCTGN (true or false)
octgn_o8d: true

# Creating CSV files for RingsDB (true or false)
ringsdb_csv: true

# Creating JSON files for Hall of Beorn (true or false)
hallofbeorn_json: true

# List of image outputs
outputs:
  English:
    - db
    - octgn
#    - pdf_a4
#    - pdf_letter
#    - makeplayingcards_zip
#    - makeplayingcards_7z
#    - drivethrucards_zip
#    - drivethrucards_7z
#    - mbprint_zip
#    - mbprint_7z
#    - mbprint_pdf
  German:
#    - db
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - makeplayingcards_zip
#    - makeplayingcards_7z
#    - drivethrucards_zip
#    - drivethrucards_7z
#    - mbprint_zip
#    - mbprint_7z
#    - mbprint_pdf
  Spanish:
#    - db
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - makeplayingcards_zip
#    - makeplayingcards_7z
#    - drivethrucards_zip
#    - drivethrucards_7z
#    - mbprint_zip
#    - mbprint_7z
#    - mbprint_pdf
  French:
#    - db
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - makeplayingcards_zip
#    - makeplayingcards_7z
#    - drivethrucards_zip
#    - drivethrucards_7z
#    - mbprint_zip
#    - mbprint_7z
#    - mbprint_pdf
  Polish:
#    - db
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - makeplayingcards_zip
#    - makeplayingcards_7z
#    - drivethrucards_zip
#    - drivethrucards_7z
#    - mbprint_zip
#    - mbprint_7z
#    - mbprint_pdf
  Italian:
#    - db
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - makeplayingcards_zip
#    - makeplayingcards_7z
#    - drivethrucards_zip
#    - drivethrucards_7z
#    - mbprint_zip
#    - mbprint_7z
#    - mbprint_pdf