# Google Sheets ID of the cards spreadsheet
sheet_gdid: ***

# Local path to the artwork folder
artwork_path: C:\Google Drive\CardImages

# Path to GIMP console executable
gimp_console_path: C:\Program Files\GIMP 2\bin\gimp-console-2.10.exe

# Path to ImageMagick executable
magick_path: C:\Program Files\ImageMagick-7.0.10-Q16-HDRI\magick.exe

# Path to id_rsa key to upload files to DragnCards (may be empty)
dragncards_id_rsa_path: id_rsa

# Path to remote logs folder (may be empty)
remote_logs_path: C:\Google Drive\Logs

# Path to OCTGN set.xml destination folder (may be empty)
octgn_set_xml_destination_path:

# Path to OCTGN set.xml scratch destination folder (may be empty)
octgn_set_xml_scratch_destination_path:

# Path to OCTGN .o8d destination folder (may be empty)
octgn_o8d_destination_path:

# Path to OCTGN .o8d scratch destination folder (may be empty)
octgn_o8d_scratch_destination_path:

# Path to OCTGN image destination folder (may be empty)
octgn_image_destination_path: C:\Google Drive\Playtesting\OCTGN Files\ImageDatabase

# Path to DB destination folder (may be empty)
db_destination_path: C:\Google Drive\RenderedImages

# Path to TTS destination folder (may be empty)
tts_destination_path: C:\Google Drive\TTS

# Remote DragnCards path to image folder
dragncards_remote_image_path: /mnt/volume_postgres/cards/English/

# Remote DragnCards path to JSON folder
dragncards_remote_json_path: /var/www/dragncards.com/dragncards/frontend/src/cardDB/ALeP/

# Remote DragnCards path to .o8d folder
dragncards_remote_deck_path: /var/www/dragncards.com/Lord-of-the-Rings/o8g/Decks/Quests/QPT-AleP-Playtest/

# Whether to reprocess all cards (true)
# or update only the cards, changed since the previous script run (false)
reprocess_all: false

# Whether to reprocess all cards even when reprocess_all=false if the previous script run didn't succeed (true or false)
reprocess_all_on_error: true

# Process only "selected" rows (true or false)
selected_only: false

# Stop processing if there are no spreadsheet changes (true or false)
exit_if_no_spreadsheet_changes: false

# Run sanity check for all sets (true or false)
run_sanity_check_for_all_sets: false

# Number of parallel processes to use ("default" means "cpu_count() - 1", but not more than 4)
parallelism: default

# List of set IDs to work on
set_ids:
  - all  # all non-scratch sets
  - all_scratch  # all scratch sets
#  - 8a3273ca-1ccd-4e07-913b-766fcc49fe6f

# List of set IDs to ignore
ignore_set_ids:
  - 8a3273ca-1ccd-4e07-913b-766fcc49fe6f

# List of set IDs to copy to OCTGN image destination
set_ids_octgn_image_destination:
#  - all  # all non-scratch sets
#  - 8a3273ca-1ccd-4e07-913b-766fcc49fe6f

# Creating set.xml files for OCTGN (true or false)
octgn_set_xml: false

# Creating .o8d files for OCTGN and DragnCards (true or false)
octgn_o8d: true

# Creating CSV files for RingsDB (true or false)
ringsdb_csv: false

# Creating JSON files for DragnCards (true or false)
dragncards_json: true

# Creating JSON files for Hall of Beorn (true or false)
hallofbeorn_json: false

# Creating CSV files for the French database sda.cgbuilder.fr (true or false)
frenchdb_csv: false

# Creating CSV files for the Spanish database susurrosdelbosqueviejo.com (true or false)
spanishdb_csv: false

# Creating artwork for DragnCards proxy images (true or false)
renderer_artwork: true

# Creating DragnCards proxy images (true or false)
renderer: false

# Uploading pixel-perfect images to DragnCards (true or false)
upload_dragncards: true

# Uploading lightweight outputs to DragnCards (true or false)
upload_dragncards_lightweight: false

# DragnCards hostname: username@hostname (may be empty)
dragncards_hostname: 

# Updating ringsdb.com (true or false)
update_ringsdb: false

# ringsdb.com URL (may be empty)
ringsdb_url: 

# ringsdb.com session id: <PHPSESSID>|<REMEMBERME> (may be empty)
ringsdb_sessionid: 

# List of image outputs
outputs:
  English:
    - db
#    - dragncards_hq
    - octgn
#    - pdf_a4
#    - pdf_letter
#    - mbprint_7z
#    - mbprint_pdf_7z
#    - makeplayingcards_7z
#    - genericpng_7z
#    - genericpng_pdf_a4_7z
#    - genericpng_pdf_letter_7z
#    - rules_pdf
    - tts
  German:
#    - db
#    - dragncards_hq
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - mbprint_7z
#    - mbprint_pdf_7z
#    - makeplayingcards_7z
#    - genericpng_7z
#    - genericpng_pdf_a4_7z
#    - genericpng_pdf_letter_7z
#    - rules_pdf
#    - tts
  Spanish:
#    - db
#    - dragncards_hq
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - mbprint_7z
#    - mbprint_pdf_7z
#    - makeplayingcards_7z
#    - genericpng_7z
#    - genericpng_pdf_a4_7z
#    - genericpng_pdf_letter_7z
#    - rules_pdf
#    - tts
  French:
#    - db
#    - dragncards_hq
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - mbprint_7z
#    - mbprint_pdf_7z
#    - makeplayingcards_7z
#    - genericpng_7z
#    - genericpng_pdf_a4_7z
#    - genericpng_pdf_letter_7z
#    - rules_pdf
#    - tts
  Polish:
#    - db
#    - dragncards_hq
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - mbprint_7z
#    - mbprint_pdf_7z
#    - makeplayingcards_7z
#    - genericpng_7z
#    - genericpng_pdf_a4_7z
#    - genericpng_pdf_letter_7z
#    - rules_pdf
#    - tts
  Italian:
#    - db
#    - dragncards_hq
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - mbprint_7z
#    - mbprint_pdf_7z
#    - makeplayingcards_7z
#    - genericpng_7z
#    - genericpng_pdf_a4_7z
#    - genericpng_pdf_letter_7z
#    - rules_pdf
#    - tts
  Portuguese:
#    - db
#    - dragncards_hq
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - mbprint_7z
#    - mbprint_pdf_7z
#    - makeplayingcards_7z
#    - genericpng_7z
#    - genericpng_pdf_a4_7z
#    - genericpng_pdf_letter_7z
#    - rules_pdf
#    - tts
