# Google Drive ID of the cards spreadsheet (leave empty to use a local copy)
sheet_gdid: ***

# Local path to the artwork folder
artwork_path: C:\Google Drive\CardImages\

# Path to GIMP console executable
gimp_console_path: C:\Program Files\GIMP 2\bin\gimp-console-2.10.exe

# Path to ImageMagick executable
magick_path: C:\Program Files\ImageMagick-7.0.10-Q16-HDRI\magick.exe

# Path to OCTGN set.xml destination folder (may be empty)
octgn_set_xml_destination_path: C:\Google Drive\OCTGN Files\Set Folders

# Path to OCTGN set.xml scratch destination folder (may be empty)
octgn_set_xml_scratch_destination_path: C:\Google Drive\OCTGN Files\Scratch Set Folders

# Path to OCTGN .o8d destination folder (may be empty)
octgn_o8d_destination_path: C:\Google Drive\OCTGN Files\Encounter Decks

# Path to OCTGN .o8d scratch destination folder (may be empty)
octgn_o8d_scratch_destination_path: C:\Google Drive\OCTGN Files\Scratch Encounter Decks

# Whether to reprocess all cards (true)
# or update only the cards, changed since the previous script run (false)
reprocess_all: true

# Process only "selected" rows (true or false)
selected_only: false

# Number of parallel processes to use ("default" means "cpu_count() - 1")
parallelism: default

# List of set IDs to work on
set_ids:
  - all  # all non-scratch sets
#  - all_scratch  # all scratch sets
#  - 8a3273ca-1ccd-4e07-913b-766fcc49fe6f  # ALeP - Children of Eorl

# Creating set.xml files for OCTGN (true or false)
octgn_set_xml: true

# Creating .o8d files for OCTGN (true or false)
octgn_o8d: true

# Creating CSV files for RingsDB (true or false)
ringsdb_csv: true

# Creating JSON files for Hall of Beorn (true or false)
hallofbeorn_json: true

# List of image outputs
outputs:
  English:
    - db
    - octgn
#    - pdf_a4
#    - pdf_letter
#    - makeplayingcards_zip
#    - makeplayingcards_7z
#    - drivethrucards_zip
#    - drivethrucards_7z
#    - mbprint_zip
#    - mbprint_7z
#    - mbprint_pdf
  German:
#    - db
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - makeplayingcards_zip
#    - makeplayingcards_7z
#    - drivethrucards_zip
#    - drivethrucards_7z
#    - mbprint_zip
#    - mbprint_7z
#    - mbprint_pdf
  Spanish:
#    - db
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - makeplayingcards_zip
#    - makeplayingcards_7z
#    - drivethrucards_zip
#    - drivethrucards_7z
#    - mbprint_zip
#    - mbprint_7z
#    - mbprint_pdf
  French:
#    - db
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - makeplayingcards_zip
#    - makeplayingcards_7z
#    - drivethrucards_zip
#    - drivethrucards_7z
#    - mbprint_zip
#    - mbprint_7z
#    - mbprint_pdf
  Polish:
#    - db
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - makeplayingcards_zip
#    - makeplayingcards_7z
#    - drivethrucards_zip
#    - drivethrucards_7z
#    - mbprint_zip
#    - mbprint_7z
#    - mbprint_pdf
  Italian:
#    - db
#    - octgn
#    - pdf_a4
#    - pdf_letter
#    - makeplayingcards_zip
#    - makeplayingcards_7z
#    - drivethrucards_zip
#    - drivethrucards_7z
#    - mbprint_zip
#    - mbprint_7z
#    - mbprint_pdf